name: nakama
data_dir: /nakama/data

logger:
  level: INFO
  stdout: true

database:
  driver: cockroach
  address: root@cockroachdb:26257
  ssl_mode: disable

socket:
  server_key: defaultkey
  port: 7350

console:
  port: 7351
  username: admin
  password: password

